### PR TITLE
Added a style file and styling fonts

### PR DESCRIPTION
**Pull request by vikasbhalla05**
Have done some major file changes
but haven't touched any functionality files

here is the result👇
image

### CODE REVIEW

**Comment by vikasbhalla05** [comment]
I would suggest merging
made it responsive too
and more readable

**Comment by Rasesh2005** [comment]
It would be amazing if you would customise button design in your style as well, button looks a bit off the cursive style you are following

**Comment by vikasbhalla05** [comment]
Yaa what should I do
make the button corner rounded?

**Comment by Rasesh2005** [comment]
Yes and change border colour to match other styles

**Comment by vikasbhalla05** [comment]
Hey can you accept or merge this PR under hacktoberfest so I can create another ?

**Comment by vikasbhalla05** [comment]
This PR is not closed or merged so I cannot make a new one
I've made the changes 👇

image

**Comment by vikasbhalla05** [comment]
There is still conflict in README

**Comment by Rasesh2005** [comment]
Yeah, can you fix it and send new pr? I intend to merge that one. If yes i will close this pr,

**Comment by vikasbhalla05** [comment]
How can I fix it?

**Comment by Rasesh2005** [comment]
Take html css files from this pr , make a new forked repo And change the files html and css

**Comment by Rasesh2005** [comment]
Will you do it? If yes, then close the current PR

**Comment by vikasbhalla05** [comment]
Okk I will change the HTML and CSS files and send in a new PR

**Pull request closed without merging**
