### PR TITLE
modified dark mode

### PR DESCRIPTION
**Pull request by deepyaman-das**
image

### CODE REVIEW

**Comment by Rasesh2005** [comment]
Put a text to left of button saying “Dark Mode”

**Comment by deepyaman-das** [comment]
few changes my friend wants to make please merge this then he can work on it.

**Comment by Rasesh2005** [comment]
The switch will confuse people using it thats y

**Comment by deepyaman-das** [comment]
ok I am doing

**Comment by deepyaman-das** [comment]
now merge my PR

**Comment by deepyaman-das** [comment]
image

**Comment by deepyaman-das** [comment]
you have a different branch as live website change your source to master.

**Comment by Rasesh2005** [comment]
Will do it soon …

**Pull request merged**
