### PR TITLE
Added Dark mode

### PR DESCRIPTION
**Pull request by deepyaman-das**
Few Screenshots of my work.
image
image
Merge my PR for hacktoberfest.

### CODE REVIEW

**Comment by Rasesh2005** [comment]
Can you make a switch? And place the darks mode option on top right corner? And send SS again?

**Comment by deepyaman-das** [comment]
yes accept is pr again i will change it

**Comment by Rasesh2005** [comment]
In dark mode change button border too in next pr

**Comment by deepyaman-das** [comment]
hacktoberfest-accepted tag??

**Pull request merged**
