### PR TITLE
I changed html,css and js.

### PR DESCRIPTION
**Pull request by ItsRoy69**
I worked on glass morphism,javascript animation,css fonts,background colour.

### CODE REVIEW

**Comment by ItsRoy69** [comment]
I changed the style,modified the html fonts,worked on glass morphism and javascript animation.

**Comment by Rasesh2005** [comment]
Can You Send Me sample snapshots of your Final Product??

**Comment by Rasesh2005** [comment]
Also, I see the you have created a new Style.css file but not linked it to the html file on which the website functions...

**Comment by ItsRoy69** [comment]
Sure i'll

**Comment by ItsRoy69** [comment]
Screenshot

**Comment by Rasesh2005** [comment]
Not a good format bro , I prefer texts to be white and heading board and reset button one below other not side by side

**Pull request closed without merging**
